filetype plugin indent on
syntax on
"vnoremap \y :w !pbcopy -selection clipboard<CR><CR>
set number
set path+=**
set tabstop=4
set shiftwidth=4
set hlsearch
set expandtab
set wildmenu
set incsearch
set hidden
set ignorecase
set smartcase
set gp=git\ grep\ -n
set ruler
set re=0
